# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and tsconfig
COPY package*.json tsconfig.json ./

# Install dependencies without running lifecycle scripts
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (though stdio mode is used)
EXPOSE 6001

# Run the server in stdio mode by not passing the '--sse' flag
CMD ["node", "dist/index.js", "--port", "6001"]
